### ISSUE TITLE
Mention on bup web site

### ISSUE THREAD

**Issue by lelutin** [skorokithakis/encbup#2]
Hey there, I just found this project out through a post about backups on HN, and I wanted to let you know that I've added a mention to your project on bup's web site in the "Related projects" section:

https://bup.github.io/

let me know if the description I put up doesn't reflect reality (you can also open an issue or a pull request on the web site project https://github.com/bup/bup.github.io)

**Comment by skorokithakis** [comment]
Looks good, thanks! There's only one typo, "ingests".
